### ISSUE TITLE
How to dynamic get value with key from request?

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/input-http#17]
Like RequestModel

```
$this->getAttributeValue('query.page_size')
```

RequestModel is deprecated?

**Comment by hiscaler** [comment]
I want get value by dynamic key,  but you example is special key

**Comment by Tigrov** [comment]
Try this:

```php
Route::get('/{key:\w+}/{value:\w+}')
        ->action([Controller::class, 'view'])
        ->name('view'),
```

Then you can build urls with dynamic key

```php
$urlGenerator->generate('view', ['key' => $key, 'value' => $value]);
```

**Comment by hiscaler** [comment]
@Tigrov it's not like that
Example:
i hava a api like: /api/users

client has a request like: /api/users?name=john&age=1 show he get name is john and age eq 1 year data.

name and age key i want get value from user request url.

**Comment by Tigrov** [comment]
Maybe something like this

```php
final class ViewController
{
    public function view(private CurrentRoute $currentRoute): ResponseInterface
    {
        $arguments = $this->currentRoute->getArguments();
        ...
    }
}
```

`$arguments` will have (key => value) array

**Comment by hiscaler** [comment]
Ok, thank you , try it later

**Comment by Tigrov** [comment]
In your case perhaps `ServerRequestInterface` is more suitable

```php
final class ViewController
{
    public function view(private ServerRequestInterface $request): ResponseInterface
    {
        $values = $request->getQueryParams();
        ...
    }
}
```

**Comment by vjik** [comment]
ServerRequestInterface resolved in action only.
