### ISSUE TITLE
Rename `#[Request]` to `#[RequestAttribute]`?

### ISSUE THREAD

**Issue by arogachev** [yiisoft/input-http#24]
What if for example we'll add the mapping from request's header values in the future? A more specific name would be better here IMO.

**Comment by vjik** [comment]
For headers better use name `Header`. For example, for query string arguments used `Query`, for body parameters used `Body`, and etc.

I think, `Request` is good name.

**Comment by arogachev** [comment]
OK, let's leave it like that for now. :ok_hand:
