### ISSUE TITLE
How to upload multi files one time?

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/input-http#39]
### What steps will reproduce the problem?
```php
#[UploadedFiles('certifications')]
private ?UploadedFileInterface $certifications = null;
```
### What is the expected result?
get a array of files
### What do you get instead?
only get last one file.

**Comment by vjik** [comment]
There is invalid type in your code. Use `?array` instead of `?UploadedFileInterface`:

```php
#[UploadedFiles('certifications')]
private ?array $certifications = null;
```

Also check that file input name has postfix `[]`: `name="certifications[]"`.

**Comment by hiscaler** [comment]
Yes, you are right, Thank you.
